/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "clock.h"

uint32_t auc[2048]__attribute((section(".ExRam")));


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "clock", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "hours", ID_TEXT_0, 10, 78, 84, 68, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "minutes", ID_TEXT_1, 128, 81, 95, 66, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 102, 81, 23, 65, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "weekday", ID_TEXT_3, 15, 30, 129, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "date", ID_TEXT_4, 155, 31, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "seconds", ID_TEXT_5, 89, 159, 52, 37, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'clock'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_TRANSPARENT);
    //
    // Initialization of 'hours'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_D64);
    TEXT_SetText(hItem, "21");
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'minutes'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "37");
    TEXT_SetFont(hItem, GUI_FONT_D64);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, ":");
    TEXT_SetFont(hItem, GUI_FONT_D48);
    TEXT_SetTextColor(hItem, 0x000000FF);
    //
    // Initialization of 'weekday'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "poniedzialek");
    TEXT_SetTextColor(hItem, 0x00008000);
    //
    // Initialization of 'date'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "12.04");
    TEXT_SetTextColor(hItem, 0x00008000);
    //
    // Initialization of 'seconds'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetText(hItem, "48");
    TEXT_SetTextColor(hItem, 0x000000FF);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createclock
*/

WM_HWIN Createclock(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

void Clock( void * pvParameters)
{
	WM_HWIN hWinclock;
	hWinclock  = Createclock();
	vTaskDelete(Menu_Handle);
	vTaskDelete(Heading_Handle);
	RTC_TimeTypeDef time;
	GUI_SetOrientation(0);
	FRESULT f=0;
	FIL fsrc;
	FATFS fs;

	while(1)
	{
		if(vol_up)
		{
			  while(1){CPU_OFF;}
			  delay(100);
		}
		else
		{
			  CPU_ON;
		}
		vTaskDelay(100);
		RTC_GetTime(RTC_Format_BIN,&time);
		WM_HWIN minutes = WM_GetDialogItem(hWinclock, ID_TEXT_1);
		TEXT_SetText(minutes,itoa(time.RTC_Minutes,t,10));
		WM_HWIN hours = WM_GetDialogItem(hWinclock, ID_TEXT_0);
		TEXT_SetText(hours,itoa(time.RTC_Hours,t,10));
		WM_HWIN seconds = WM_GetDialogItem(hWinclock, ID_TEXT_5);
		TEXT_SetText(seconds,itoa(time.RTC_Seconds,t,10));

		if(time.RTC_Hours==21 && time.RTC_Minutes==37 && time.RTC_Seconds<4)
		{
			taskENTER_CRITICAL();
//			jpeg_create_decompress(&cinfo);
//			cinfo.err = jpeg_std_error(&jerr);
//		    f=f_open(&fsrc,"0:papiez.jpg", FA_READ | FA_OPEN_EXISTING );
//		    jpeg_decode(&fsrc, 320, auc, 0);
//		    jpeg_finish_decompress(&cinfo);
//		    jpeg_destroy_decompress(&cinfo);
			bitmap_RGB("0:papa.rgb",0,0,226,320);
			for(int l=0;l<0xfffff;l++){};
		    taskEXIT_CRITICAL();
		}
		else{
			WM_Paint(hWinclock);

		}

	}
}
